### ISSUE TITLE
Nextflow error: Repository may be corrupted

### ISSUE THREAD

**Issue by adomingues** [bigbio/proteomicstmt#22]
I was trying to test the pipeline using the test data only, but ran into issues:

```bash
../nextflow_dev run bigbio/proteomicstmt -profile singularity,test -r dev
N E X T F L O W  ~  version 20.11.0-edge
Unknown error accessing project `bigbio/proteomicstmt` -- Repository may be corrupted: /mnt/projects/genomics/.nextflow/assets/bigbio/proteomicstmt
```

This happened even if:

- a commit hash was used in `-r`
-  nextflow pull`  was used before running the pipeline
- the repo `ypriverol/proteomicstmt` was used
- a different nextflow version was used. 

Thanks!

**Comment by ypriverol** [comment]
@adomingues do current version of the workflow is working. We are still doing benchmark and refinements
